[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bet_contract = "FBzKRcpiLyb6zMM8XVU8mBvJdHxyknGBioihUGFxcuh4"

# [registry]
# url = "https://api.apr.dev"

[registry]
url = "http://localhost:8899"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
